local:
  host: http://localhost:3000/facilities-management
  account_username:
  account_password:
cmpdev:
  host: https://cmp.cmpdev.crowncommercial.gov.uk/facilities-management
  account_username:
  account_password:
  buyer_username:
  buyer_password:
preview:
  host: https://marketplace.preview.crowncommercial.gov.uk/facilities-management
  account_username:
  account_password:
